org: lucasprestes
app: image-analysis
service: image-analysis

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  image-analysis:
    handler: handler.main
    events:
      - http:
          path: analyse
          method: get